/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ArticlePagination: typeof import('./src/components/ArticlePagination.vue')['default']
    ArticlePreview: typeof import('./src/components/ArticlePreview.vue')['default']
    ArticleToggle: typeof import('./src/components/ArticleToggle.vue')['default']
    AuthPage: typeof import('./src/components/AuthPage.vue')['default']
    Brands: typeof import('./src/components/Home/Brands.vue')['default']
    DeleteArticleButton: typeof import('./src/components/DeleteArticleButton.vue')['default']
    EditArticleButton: typeof import('./src/components/EditArticleButton.vue')['default']
    ErrorMessages: typeof import('./src/components/ErrorMessages.vue')['default']
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    ForYouProducts: typeof import('./src/components/Home/ForYouProducts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SameProductCollection: typeof import('./src/components/Home/SameProductCollection.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TopCategories: typeof import('./src/components/Home/TopCategories.vue')['default']
  }
}
