/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ArticlePagination: typeof import('./src/components/ArticlePagination.vue')['default']
    ArticlePreview: typeof import('./src/components/ArticlePreview.vue')['default']
    ArticleToggle: typeof import('./src/components/ArticleToggle.vue')['default']
    AuthPage: typeof import('./src/components/AuthPage.vue')['default']
    Brands: typeof import('./src/components/Home/Brands.vue')['default']
    BreadCrum: typeof import('./src/components/support/BreadCrum.vue')['default']
    CartPopup: typeof import('./src/components/cart/CartPopup.vue')['default']
    Categories: typeof import('./src/components/market/Categories.vue')['default']
    CategoryImages: typeof import('./src/components/market/CategoryImages.vue')['default']
    Checkout: typeof import('./src/components/Checkout.vue')['default']
    DateFilters: typeof import('./src/components/CommonComponenets/DateFilters.vue')['default']
    DeleteArticleButton: typeof import('./src/components/DeleteArticleButton.vue')['default']
    EditArticleButton: typeof import('./src/components/EditArticleButton.vue')['default']
    ErrorMessages: typeof import('./src/components/ErrorMessages.vue')['default']
    EventDetailMain: typeof import('./src/components/CommonComponenets/EventsComponents/EventDetailMain.vue')['default']
    EventImageComponent: typeof import('./src/components/CommonComponenets/EventsComponents/EventImageComponent.vue')['default']
    EventQRScan: typeof import('./src/components/CommonComponenets/EventsComponents/EventQRScan.vue')['default']
    FamousReturnats: typeof import('./src/components/resturant/FamousReturnats.vue')['default']
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    Favourites: typeof import('./src/components/Favourites.vue')['default']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    ForYouProducts: typeof import('./src/components/Home/ForYouProducts.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    Login: typeof import('./src/components/auth/Login.vue')['default']
    OderHistory: typeof import('./src/components/OderHistory.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductDetail: typeof import('./src/components/product/ProductDetail.vue')['default']
    ProductImages: typeof import('./src/components/product/ProductImages.vue')['default']
    ProfileModal: typeof import('./src/components/auth/ProfileModal.vue')['default']
    RecomendedProducts: typeof import('./src/components/product/RecomendedProducts.vue')['default']
    RecProductCard: typeof import('./src/components/product/RecProductCard.vue')['default']
    RelatedProducts: typeof import('./src/components/market/RelatedProducts.vue')['default']
    ResturantsList: typeof import('./src/components/resturant/ResturantsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SameProductCollection: typeof import('./src/components/Home/SameProductCollection.vue')['default']
    Scity: typeof import('./src/components/Scity.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TopCategories: typeof import('./src/components/Home/TopCategories.vue')['default']
    TranslateWrapper: typeof import('./src/components/TranslateWrapper.vue')['default']
  }
}
