/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
  export interface RouteNamedMap {
    'Root': RouteRecordInfo<'Root', '/', Record<never, never>, Record<never, never>>,
    'ComponentsPopularTags': RouteRecordInfo<'ComponentsPopularTags', '/components/PopularTags', Record<never, never>, Record<never, never>>,
  }  '$All': RouteRecordInfo<'$All', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'Checkout': RouteRecordInfo<'Checkout', '/checkout', Record<never, never>, Record<never, never>>,
    'Favorites': RouteRecordInfo<'Favorites', '/favorites', Record<never, never>, Record<never, never>>,
    'Grocery': RouteRecordInfo<'Grocery', '/grocery', Record<never, never>, Record<never, never>>,
    'GroceryGroceriesComponentsGroceriesGallery': RouteRecordInfo<'GroceryGroceriesComponentsGroceriesGallery', '/grocery/GroceriesComponents/GroceriesGallery', Record<never, never>, Record<never, never>>,
    'GroceryGroceriesComponentsGroceriesHeader': RouteRecordInfo<'GroceryGroceriesComponentsGroceriesHeader', '/grocery/GroceriesComponents/GroceriesHeader', Record<never, never>, Record<never, never>>,
    'GroceryGroceriesComponentsGroceryCard': RouteRecordInfo<'GroceryGroceriesComponentsGroceryCard', '/grocery/GroceriesComponents/GroceryCard', Record<never, never>, Record<never, never>>,
    'GroceryGroceriesComponentsGroceryFilter': RouteRecordInfo<'GroceryGroceriesComponentsGroceryFilter', '/grocery/GroceriesComponents/GroceryFilter', Record<never, never>, Record<never, never>>,
    'GroceryGroceriesComponentsMerchantCard': RouteRecordInfo<'GroceryGroceriesComponentsMerchantCard', '/grocery/GroceriesComponents/MerchantCard', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'MarketElectronics': RouteRecordInfo<'MarketElectronics', '/market/electronics', Record<never, never>, Record<never, never>>,
    'OrderHistory': RouteRecordInfo<'OrderHistory', '/order-history', Record<never, never>, Record<never, never>>,
    'ProductVue': RouteRecordInfo<'ProductVue', '/product/vue', Record<never, never>, Record<never, never>>,
    'ProductsId?': RouteRecordInfo<'ProductsId?', '/products/:id?', { id?: ParamValueZeroOrOne<true> }, { id?: ParamValueZeroOrOne<false> }>,
    'ProductsComponentsArticleForm': RouteRecordInfo<'ProductsComponentsArticleForm', '/products/components/ArticleForm', Record<never, never>, Record<never, never>>,
    'ProductsComponentsCommentList': RouteRecordInfo<'ProductsComponentsCommentList', '/products/components/CommentList', Record<never, never>, Record<never, never>>,
    'ProductsCreate': RouteRecordInfo<'ProductsCreate', '/products/create', Record<never, never>, Record<never, never>>,
    'ProductsDetail': RouteRecordInfo<'ProductsDetail', '/products/detail', Record<never, never>, Record<never, never>>,
    'ProductsEditorId?': RouteRecordInfo<'ProductsEditorId?', '/products/editor/:id?', { id?: ParamValueZeroOrOne<true> }, { id?: ParamValueZeroOrOne<false> }>,
    'ProfileId?': RouteRecordInfo<'ProfileId?', '/profile/:id?', { id?: ParamValueZeroOrOne<true> }, { id?: ParamValueZeroOrOne<false> }>,
    'Register': RouteRecordInfo<'Register', '/register', Record<never, never>, Record<never, never>>,
    'Restaurants': RouteRecordInfo<'Restaurants', '/restaurants', Record<never, never>, Record<never, never>>,
    'RestaurantsDetails': RouteRecordInfo<'RestaurantsDetails', '/restaurants/details', Record<never, never>, Record<never, never>>,
    'Scity': RouteRecordInfo<'Scity', '/scity', Record<never, never>, Record<never, never>>,
    'ScityEventDetails': RouteRecordInfo<'ScityEventDetails', '/scity/event-details', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
